### ISSUE TITLE
Not working with Spree v4.0

### ISSUE THREAD

**Issue by alidawud** [spree-contrib/spree_digital#123]
Not working with Spree v4.0

**Comment by jittdev** [comment]
Yes, please update! This is a great extension for spree. Pretty please!

**Comment by halo** [comment]
Could you try https://github.com/spree-contrib/spree_digital/tree/rails_6_spree_4 and see if that works for you as well? I have currently no Spree project to so I cannot try it out. The code looks very clean though and there are quite a few tests and they all pass (great work BTW).

One question: how to provide an upgrade path from paperclip to ActiveStorage, is that dealt with by Spree itself? Do you know? @PSzyszkaSpark

**Comment by jittdev** [comment]
Thanks halo. We tried rails_6_spree_4, but there were 4 tests there that actually did fail. But we'll look at it again. On your paperclip question, the only thing we can think of is to export/import all your product/data to a spree4.0, and then just manually load your product pictures using Spree admin. Paperclip is just too different from ActiveStorage, as the latter handles files in a completely different way.

**Comment by halo** [comment]
Ok, we'll wait from [feedback from the author](https://github.com/spree-contrib/spree_digital/pull/124#issuecomment-570806925) if there are any blockers. To me this is mergable for master.

> but there were 4 tests there that actually did fail. But we'll look at it again.

Ok, let us know if anything is wrong with the branch. To me it sure looks like all tests are passing and that integration tests with capybara have been added and are also passing.

> Paperclip is just too different from ActiveStorage, as the latter handles files in a completely different way.

Actually, migrating the data is quite simple as long as both paperclip and AS are in the code at the same time, see https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md#moving-files-on-a-remote-host-s3-azure-storage-gcs-etc

My question was more directed toward getting feeling how smooth spree extensions **usually** are upgradable in a pain-free manner these days :D Maybe it's enough to make a big note in the README and CHANGELOG.

**Comment by jittdev** [comment]
ok Good to know. We were in between projects and so never had to breach the paperclip/AS upgrade question. thx.

our initial implementation of rails_6_spree_4 had several blocks where we couldn't even get the rails server to start. but like i said, we'll look at it again, probably early next week.

**Comment by damianlegawiec** [comment]
Fixed via https://github.com/spree-contrib/spree_digital/pull/124
