### ISSUE TITLE
Generator not loading with spree version 4.11.1

### ISSUE THREAD

**Issue by TechDendron** [spree-contrib/spree_digital#128]
Similar issue: https://github.com/spree-contrib/spree_editor/issues/154

Looks like with the latest spree version the generator is failed to load

<img width="1770" alt="Screenshot 2020-10-16 at 10 13 03 PM" src="https://user-images.githubusercontent.com/64126748/96285590-c8cd3900-0ffc-11eb-8d24-a772edbdda5a.png">

**Comment by damianlegawiec** [comment]
This gem was merged into Spree 4.4, so just update to the latest version
